import { Metadata } from "next";

export const sharedMetadata: Metadata = {
    metadataBase: new URL("https://what-if.rw"),
    title: "WHAT IF-Rwanda | Be the source of their smile.",
    description: "Join us in transforming lives! Your involvement can make a profound difference through volunteering, mentorship, or sponsorship. Contact us today to learn how you can help provide essential needs, emotional support, and a brighter future for vulnerable children. Together, we can be the source of their smile.",
    icons: ['/favicon.ico'],
    openGraph: {
        title: 'WHAT IF-Rwanda | Be the source of their smile.',
        description: 'Join us in transforming lives! Your involvement can make a profound difference through volunteering, mentorship, or sponsorship. Contact us today to learn how you can help provide essential needs, emotional support, and a brighter future for vulnerable children. Together, we can be the source of their smile.',
        siteName: 'WHAT IF-Rwanda',
        images: ['/opengraph-image.jpg'],
        type: 'website',
        countryName: 'RWANDA',
        url: 'https://what-if.rw',
        phoneNumbers: ['+250789553464'],
        emails: ['whatifrwanda@gmail.com'],

    },
    keywords: [
        "WHAT IF-Rwanda",
        "youth-driven movement",
        "vulnerable communities",
        "underserved communities",
        "mentorship program",
        "sponsorship program",
        "empower children",
        "volunteer Rwanda",
        "child sponsorship",
        "mentor a child",
        "Iramiro Center",
        "Inshuti zabakene",
        "Friends of the Poor",
        "Silas Gasasira",
        "Rwanda charity",
        "African Children's Choir",
        "donate Rwanda",
        "charity Rwanda",
        "support vulnerable children",
        "hope for children",
        "post-genocide Rwanda",
        "transform lives",
        "financial support for children",
        "mentor and sponsorship",
        "positive change",
        "non-profit Rwanda",
        "community involvement",
        "brighter future for children",
        "volunteer opportunities",
        "join a cause Rwanda",
        "be the source of their smile"
    ],
};